[workspace]
members = [
    "rain-aggregates",
    "rain-base",
    "rain-commands",
    "rain-core",
    "rain-model",
    "rain-projections",
    "rain-queries",
    "rain-repository",
    "rain-web",
]