[package]
name = "rain-queries"
version = "1.0.0"
authors = ["rainbing <cnrainbing@163.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
